// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOtltWXx0bJkY53c1uaLiKzhYoIkhdNI',
    appId: '1:784156680828:web:9b9c7113b0d9f668b79ff9',
    messagingSenderId: '784156680828',
    projectId: 'project-718ed',
    authDomain: 'project-718ed.firebaseapp.com',
    storageBucket: 'project-718ed.firebasestorage.app',
    measurementId: 'G-161ZRTCN0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd26B1d-NOlHmE_LbvCXsN95JUGsN-6YI',
    appId: '1:784156680828:android:b7d12e38e8d0f264b79ff9',
    messagingSenderId: '784156680828',
    projectId: 'project-718ed',
    storageBucket: 'project-718ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_TnH-sxInbPw06lNza9P28Mk_FoMxLc',
    appId: '1:784156680828:ios:a037c6b851fb4152b79ff9',
    messagingSenderId: '784156680828',
    projectId: 'project-718ed',
    storageBucket: 'project-718ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD_TnH-sxInbPw06lNza9P28Mk_FoMxLc',
    appId: '1:784156680828:ios:a037c6b851fb4152b79ff9',
    messagingSenderId: '784156680828',
    projectId: 'project-718ed',
    storageBucket: 'project-718ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOtltWXx0bJkY53c1uaLiKzhYoIkhdNI',
    appId: '1:784156680828:web:19e8522d55351d44b79ff9',
    messagingSenderId: '784156680828',
    projectId: 'project-718ed',
    authDomain: 'project-718ed.firebaseapp.com',
    storageBucket: 'project-718ed.firebasestorage.app',
    measurementId: 'G-T0PPJ77Q09',
  );

}